### ISSUE TITLE
Followers often gets stuck trying to hit the thin air and once that happens, at new areas, they will not move and refuse to attack.

### ISSUE THREAD

**Issue by danylopez123** [InfernoDragon0/COTL-Supercharged-Followers#1]
I can understand this is the first version of the mod but i've wanted to point this out because i keep having this problem that i've commented in the title.

Could this be related conflicting some mods?

**Comment by InfernoDragon0** [comment]
Hi, it would be good if you can provide the log data from the bepinex folder > logoutput.log so that i can see if theres anything interrupting the pathfinding for the followers. 

Also, which dungeon did you enter and what rooms would they not move in?

thank you 😄

**Comment by InfernoDragon0** [comment]
I have uploaded v1.0.1 with a change to how the followers would start the pathfinding coroutines. It is available on thunderstore / nexus. Let me know if it works :)

**Comment by danylopez123** [comment]
Sorry, i couldn't answer before because as soon i was done with a CotL stream i was doing yesterday and i also had your mod, i made the report, after that, i was then busy with other stuff.

Let me explain one part a bit better before you updated the mod: After the followers gets stuck hitting at thin air, it's gonna happen at every room from a dungeon area, after the next area it's loaded, that's where the followers will refuse to move and attack, this might was happening to any dungeon you go.

I've tried the new version and it seems the followers doesn't seem to get stuck.. until i've reached an area to rescue a follower at darkwoods (I was doing this from a fresh new file) and i've checked the log file and this is what i saw the last time:

[Info   :SuperchargedFollowers] target null, get closest target
[Info   :SuperchargedFollowers] target found of 
[Info   :SuperchargedFollowers] pathing to player
[Info   :SuperchargedFollowers] error pathing to player, try again later: Object reference not set to an instance of an object
[Info   :SuperchargedFollowers] target null, get closest target
[Info   :SuperchargedFollowers] target found of 
[Info   :SuperchargedFollowers] pathing to player
[Info   :SuperchargedFollowers] error pathing to player, try again later: Object reference not set to an instance of an object
[Info   :SuperchargedFollowers] target null, get closest target
[Info   :SuperchargedFollowers] target found of 
[Info   :SuperchargedFollowers] pathing to player
[Info   :SuperchargedFollowers] error pathing to player, try again later: Object reference not set to an instance of an object
[Info   :SuperchargedFollowers] target null, get closest target
[Info   :SuperchargedFollowers] target found of 
[Info   :SuperchargedFollowers] pathing to player
[Info   :SuperchargedFollowers] error pathing to player, try again later: Object reference not set to an instance of an object
[Info   :SuperchargedFollowers] target null, get closest target
[Info   :SuperchargedFollowers] target found of 
[Info   :SuperchargedFollowers] pathing to player
[Info   :SuperchargedFollowers] error pathing to player, try again later: Object reference not set to an instance of an object

When this happened, the followers got stuck hitting at thin air again but they fixed themselves at a new area.

To add an extra note, there are times that the followers can get stuck from their color charging to attack and remains with more white if an enemy gets killed before the followers attack, it's just a minor thing but doesn't bug the followers.

Here's another extra note: When using the barracs, after picking a class for a Follower, the menu won't go away and becomes kinda-buggy that i'm able to move and selecting another one while this is happening confuses the menus, it can be fixed by just cancelling after selecting a class.


EDIT: Forgot to mention that as i was posting this, CotL got a new update to celebrate the first anniversary, adding stuff from Don't Starve Together, still the mod runs fine.

**Comment by InfernoDragon0** [comment]
Thanks for the info! I think that there are some objects still marked as an enemy which is why the followers are trying to attack thin air, as well as the player object not being consistently loaded (which leads to them not pathfinding correctly). The barracks class menu is odd too, thanks for reporting that.

I will be relooking into the pathfinding logic for the followers so it shall be awhile before the next update.

**Comment by danylopez123** [comment]
No Problem!
Take your time, there's no rush.

Also, just optional but maybe try to make the followers pick random targets if there's more than 1 enemy, everyone seems to be picking the same target and that might be a bit risky in some cases, some of the followers might die at the same time.
This seems to happen at every new rooms since the followers are very close, very rarely, some of them will start picking new targets.

[This will be my only report before.. i knew there was a Discord server, so if i have something else to say, i'll send my feedback to the CotL Modding Discord server]

**Comment by InfernoDragon0** [comment]
Fixed with new pathfinding solution on update v1.0.2 cc509e7
